# Generated by Django 4.2.29 on 2026-04-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("analyst", "Analyst"), ("admin", "Admin")],
                default="user",
                max_length=20,
            ),
        ),
    ]
