# Generated by Django 4.2.29 on 2026-04-29 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                        default="system",
                        max_length=10,
                    ),
                ),
                ("default_ticker", models.CharField(blank=True, max_length=10)),
                ("alert_email", models.BooleanField(default=True)),
                ("alert_push", models.BooleanField(default=True)),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[("off", "Off"), ("daily", "Daily"), ("weekly", "Weekly")],
                        default="off",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
