# Generated by Django 4.2.29 on 2026-04-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickers", "0002_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticker",
            name="sector",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
