# Generated by Django 4.2.29 on 2026-04-11 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickers", "0002_watchlist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tickers", models.ManyToManyField(blank=True, to="tickers.ticker")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StrategyExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("event_type", models.CharField(max_length=30)),
                ("event_data", models.JSONField()),
                ("conditions_matched", models.JSONField()),
                ("actions_taken", models.JSONField()),
                ("success", models.BooleanField(default=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="strategies.strategyrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="RuleCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("sentiment_score", "Sentiment Score"),
                            ("signal", "Signal"),
                            ("rsi", "RSI"),
                            ("sma_20", "SMA 20"),
                            ("ema_50", "EMA 50"),
                            ("volume_change", "Volume Change"),
                            ("bollinger_position", "Bollinger Position"),
                            ("macd_signal", "MACD Signal"),
                            ("alert_type", "Alert Type"),
                            ("mood", "Market Mood"),
                            ("price", "Price"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("gt", ">"),
                            ("lt", "<"),
                            ("gte", ">="),
                            ("lte", "<="),
                            ("eq", "=="),
                            ("neq", "!="),
                            ("contains", "contains"),
                            ("crosses_above", "crosses above"),
                            ("crosses_below", "crosses below"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                (
                    "logical_op",
                    models.CharField(
                        choices=[("AND", "AND"), ("OR", "OR")], default="AND", max_length=3
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="strategies.strategyrule",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="RuleAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("notify", "In-app Notification"),
                            ("email", "Email"),
                            ("webhook", "Webhook"),
                            ("log", "Log"),
                            ("auto_trade", "Auto Trade (post-MVP)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("order", models.IntegerField(default=0)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="strategies.strategyrule",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
