# Generated by Django 4.2.29 on 2026-04-10 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='tickers.ticker')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
