# Generated by Django 4.2.29 on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricesnapshot",
            name="source",
            field=models.CharField(
                choices=[
                    ("alpaca_stream", "Alpaca Stream"),
                    ("alpaca_rest", "Alpaca REST"),
                    ("seed", "Seed Data"),
                ],
                db_index=True,
                default="alpaca_stream",
                max_length=32,
            ),
        ),
    ]
