# Generated by Django 4.2.29 on 2026-04-11 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickers", "0002_watchlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetrainLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("trigger_reason", models.CharField(max_length=100)),
                ("old_accuracy", models.FloatField()),
                ("new_accuracy", models.FloatField(null=True)),
                ("model_version", models.CharField(max_length=50)),
                ("training_samples", models.IntegerField()),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(null=True)),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketMoodSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("embedding", models.JSONField()),
                ("dominant_mood", models.CharField(max_length=20)),
                ("confidence", models.FloatField()),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mood_snapshots",
                        to="tickers.ticker",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ManipulationFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pattern_type", models.CharField(max_length=30)),
                ("confidence", models.FloatField()),
                ("evidence", models.JSONField()),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed", models.BooleanField(default=False)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manipulation_flags",
                        to="tickers.ticker",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
    ]
