# Generated by Django 4.2.29 on 2026-04-22 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0002_watchlist'),
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrainlog',
            name='ticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrain_logs', to='tickers.ticker'),
        ),
        migrations.AlterField(
            model_name='retrainlog',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retrainlog',
            name='model_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='retrainlog',
            name='new_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retrainlog',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='retrainlog',
            name='status',
            field=models.CharField(default='running', max_length=20),
        ),
        migrations.AlterField(
            model_name='retrainlog',
            name='training_samples',
            field=models.IntegerField(default=0),
        ),
    ]
