# Generated by Django 4.2.29 on 2026-04-29 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tickers", "0003_ticker_sector"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacktestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("signal", "Follow Signal"),
                            ("sentiment_threshold", "Sentiment Threshold"),
                        ],
                        max_length=30,
                    ),
                ),
                ("params", models.JSONField(default=dict)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("win_rate", models.FloatField(blank=True, null=True)),
                ("sharpe", models.FloatField(blank=True, null=True)),
                ("max_drawdown", models.FloatField(blank=True, null=True)),
                ("total_return", models.FloatField(blank=True, null=True)),
                ("trades", models.JSONField(default=list)),
                ("equity_curve", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "OK"), ("error", "Error")], default="ok", max_length=10
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tickers.ticker"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="analytics_b_user_id_e326de_idx"
                    )
                ],
            },
        ),
    ]
