# Generated by Django 4.2.29 on 2026-04-10 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.FloatField()),
                ('momentum', models.FloatField()),
                ('consistency', models.FloatField()),
                ('signal', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('HOLD', 'HOLD')], max_length=4)),
                ('post_count', models.IntegerField()),
                ('bullish_ratio', models.FloatField(blank=True, null=True)),
                ('normalized_index', models.FloatField(blank=True, null=True)),
                ('time_decay_score', models.FloatField(blank=True, null=True)),
                ('source_weighted_score', models.FloatField(blank=True, null=True)),
                ('positive_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('prediction_method', models.CharField(default='rule_based', max_length=20)),
                ('prediction_confidence', models.FloatField(blank=True, null=True)),
                ('feature_importances', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='tickers.ticker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('divergence', 'Divergence'), ('extreme_sentiment', 'Extreme Sentiment')], max_length=30)),
                ('sentiment', models.FloatField()),
                ('momentum', models.FloatField()),
                ('consistency', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tickers.ticker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
