# Generated by Django 4.2.29 on 2026-04-02 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tickers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignalSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sentiment", models.FloatField()),
                ("momentum", models.FloatField()),
                ("consistency", models.FloatField()),
                (
                    "signal",
                    models.CharField(
                        choices=[("BUY", "BUY"), ("SELL", "SELL"), ("HOLD", "HOLD")], max_length=4
                    ),
                ),
                ("post_count", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="tickers.ticker",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("divergence", "Divergence"),
                            ("extreme_sentiment", "Extreme Sentiment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("sentiment", models.FloatField()),
                ("momentum", models.FloatField()),
                ("consistency", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="tickers.ticker",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
