# Generated by Django 4.2.29 on 2026-04-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalsnapshot',
            name='bullish_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signalsnapshot',
            name='feature_importances',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signalsnapshot',
            name='negative_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signalsnapshot',
            name='neutral_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signalsnapshot',
            name='normalized_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signalsnapshot',
            name='positive_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signalsnapshot',
            name='prediction_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signalsnapshot',
            name='prediction_method',
            field=models.CharField(default='rule_based', max_length=20),
        ),
        migrations.AddField(
            model_name='signalsnapshot',
            name='source_weighted_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signalsnapshot',
            name='time_decay_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
