# Generated by Django 4.2.29 on 2026-04-10 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("signals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignalAccuracy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("predicted", models.CharField(max_length=4)),
                ("actual_direction", models.CharField(max_length=4)),
                ("price_at_signal", models.DecimalField(decimal_places=4, max_digits=12)),
                ("price_after_1h", models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                (
                    "price_after_24h",
                    models.DecimalField(decimal_places=4, max_digits=12, null=True),
                ),
                ("accuracy_1h", models.BooleanField(null=True)),
                ("accuracy_24h", models.BooleanField(null=True)),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signal_snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accuracy",
                        to="signals.signalsnapshot",
                    ),
                ),
            ],
        ),
    ]
