# Generated by Django 4.2.29 on 2026-04-10 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tickers", "0002_watchlist"),
        ("signals", "0002_signalaccuracy"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("input_summary", models.JSONField()),
                ("scoring_detail", models.JSONField()),
                ("engine_output", models.JSONField()),
                ("alerts_triggered", models.JSONField(default=list)),
                (
                    "signal_snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_log",
                        to="signals.signalsnapshot",
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tickers.ticker"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
