# Generated by Django 4.2.29 on 2026-04-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signals", "0003_decisionlog"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="decisionlog",
            index=models.Index(
                fields=["ticker", "-timestamp"], name="signals_dec_ticker__2cf4e5_idx"
            ),
        ),
    ]
