# Generated by Django 4.2.29 on 2026-04-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_decisionlog_signals_dec_ticker__2cf4e5_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertflag',
            name='type',
            field=models.CharField(choices=[('divergence', 'Divergence'), ('extreme_sentiment', 'Extreme Sentiment'), ('hype_fade', 'Hype Fade')], max_length=30),
        ),
    ]
