# Generated by Django 4.2.29 on 2026-04-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_alter_alertflag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertflag',
            name='type',
            field=models.CharField(choices=[('divergence', 'Divergence'), ('extreme_sentiment', 'Extreme Sentiment'), ('hype_fade', 'Hype Fade'), ('pump_suspected', 'Pump Suspected')], max_length=30),
        ),
    ]
