# Generated by Django 4.2.29 on 2026-04-02 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tickers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("reddit", "Reddit"), ("stocktwits", "StockTwits")], max_length=20
                    ),
                ),
                ("external_id", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("cleaned_text", models.TextField(blank=True)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                (
                    "sentiment_label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("posted_at", models.DateTimeField()),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="tickers.ticker",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_at"],
                "unique_together": {("source", "external_id")},
            },
        ),
    ]
