# Generated by Django 4.2.29 on 2026-04-10 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('reddit', 'Reddit'), ('stocktwits', 'StockTwits')], max_length=20)),
                ('external_id', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('content', models.TextField()),
                ('cleaned_text', models.TextField(blank=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], max_length=20)),
                ('positive_prob', models.FloatField(blank=True, null=True)),
                ('negative_prob', models.FloatField(blank=True, null=True)),
                ('neutral_prob', models.FloatField(blank=True, null=True)),
                ('posted_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tickers.ticker')),
            ],
            options={
                'ordering': ['-posted_at'],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
