# Generated by Django 4.2.29 on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialpost",
            name="source",
            field=models.CharField(
                choices=[
                    ("reddit", "Reddit"),
                    ("stocktwits", "StockTwits"),
                    ("news_google", "Google News"),
                    ("news_yahoo", "Yahoo News"),
                    ("news_alpaca", "Alpaca News"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="socialpost",
            unique_together={("ticker", "source", "external_id")},
        ),
    ]
