# Generated by Django 4.2.29 on 2026-04-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='negative_prob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='neutral_prob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='positive_prob',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
