# Generated by Django 4.2.29 on 2026-04-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_socialpost_negative_prob_socialpost_neutral_prob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialpost",
            name="title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
